### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by ligi** [proofcarryingdata/zupoll#61] opened 2023-07-08 17:31 UTC
When creating a poll the app crashed like this:

![image](https://github.com/proofcarryingdata/zupoll/assets/111600/079270f1-8fbb-4cf5-bb35-edc3fcc0d765)

in the console I see:

```
amework-19f3649580393c10.js:9 RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at create-ballot-75e27e1cf39365ac.js:1:13058
    at X (create-ballot-75e27e1cf39365ac.js:1:13085)
    at ab (framework-19f3649580393c10.js:9:60915)
    at ud (framework-19f3649580393c10.js:9:72801)
    at i (framework-19f3649580393c10.js:9:120370)
    at oO (framework-19f3649580393c10.js:9:99112)
    at framework-19f3649580393c10.js:9:98979
    at oF (framework-19f3649580393c10.js:9:98986)
    at ox (framework-19f3649580393c10.js:9:95738)
a5 @ framework-19f3649580393c10.js:9
main-54379c1fb512e6dc.js:1 RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at create-ballot-75e27e1cf39365ac.js:1:13058
    at X (create-ballot-75e27e1cf39365ac.js:1:13085)
    at ab (framework-19f3649580393c10.js:9:60915)
    at ud (framework-19f3649580393c10.js:9:72801)
    at i (framework-19f3649580393c10.js:9:120370)
    at oO (framework-19f3649580393c10.js:9:99112)
    at framework-19f3649580393c10.js:9:98979
    at oF (framework-19f3649580393c10.js:9:98986)
    at ox (framework-19f3649580393c10.js:9:95738)
K @ main-54379c1fb512e6dc.js:1
main-54379c1fb512e6dc.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K
```

**Comment by ichub** [comment] 2023-07-17 09:25
duplicate of #45

**Closed** 2023-07-18 09:21 UTC
Labels: bug
